### ISSUE TITLE
Needs more currying

### ISSUE THREAD

**Issue by robertbastian** [amnn/js-from-scratch#1]
For example

`const COMP  = (f, g) => (x) => f(g(x));`

should be

`const COMP  = (f) => (g) => (x) => f(g(x));`

**Comment by amnn** [comment]
Need is a strong word, @robertbastian. The two definitions are isomorphic, and JavaScript's function application syntax requires us to choose carefully, where currying might be useful. 

For composition, I argue that people are more likely to partially apply `COMP` to two functions rather than to one.

**Comment by robertbastian** [comment]
Not as pretty though...

**Comment by amnn** [comment]
I didn't really want to have to explain currying in this talk, but apart from that, I don't think I agree that it looks prettier, for instance: 

```
const ADD = (m, n) => (s, z) => m(s, n(s, z));
```

Becomes

```
const ADD = (m) => (n) => (s) => (z) => m(s)(n(s)(z));
```

When fully curried. The extra parens hide what's significant, just like the currying hides what is significant about the encoding.

**Comment by robertbastian** [comment]
Fair enough. When's the talk?

**Comment by amnn** [comment]
June 15th, 7pm at the Story museum!

http://www.meetup.com/JSOxford/events/231241768/
